from enum import Enum

class Area(Enum):
    VENTAS = "VENTAS"
    FINANZAS = "FINANZAS"
    OPERACIONES = "OPERACIONES"
    RECURSOS_HUMANOS = "RECURSOS_HUMANOS"
    LEGAL = "LEGAL"
    TECNOLOGIA = "TECNOLOGIA"
    MARKETING = "MARKETING"
    PRODUCCION = "PRODUCCION"